---
apiVersion: v1
kind: Service
metadata:
  name: computing-svc
  labels:
    app: computing-server
spec:
  type: ClusterIP
  selector:
    app: computing-server
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: computing-server
  labels:
    app: computing-server
spec:
  selector:
    matchLabels:
      app: computing-server
  template:
    metadata:
      labels:
        app: computing-server
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
        - name: computing-server
          image: docker.io/library/computing-server:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
