---
apiVersion: v1
kind: Service
metadata:
  name: redis-client-svc
spec:
  selector:
    app: redis-client-svc
  ports:
    - port: 80
      targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-client
spec:
  selector:
    matchLabels:
      app: redis-client
  template:
    metadata:
      labels:
        app: redis-client
    spec:
      containers:
        - name: nginx-redis-client
          image: nginx:alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
        - name: redis-client
          image: kofeebrian/redis-client:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4000
