version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    command: [nginx-debug, "-g", "daemon off;"]
    ports:
      - 80:80
      - 443:443
