version: "3"
services:
  redis-client:
    build:
      context: ./app
    depends_on:
      - redis
    environment:
      - REDIS_PORT=6379

  nginx-redis-client:
    restart: always
    build:
      context: ./nginx
    ports:
      - 3001:80
    links:
      - redis-client

  redis:
    image: redis
    ports:
      - 6379:6379
