version: "3"
services:
  redis-client:
    image: kofeebrian/redis-client:v1
    container_name: redis-client
    build:
      context: ./app
    depends_on:
      - redis
    environment:
      - REDIS_PORT=6379

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
